In [2]:
import numpy as np

lst = [1, 2, 3, 2]
lst[2]

3

In [3]:
foot = [265, 290, 270, 285, 260, 235]
foot

[265, 290, 270, 285, 260, 235]

In [4]:
tall = [[177,1], [183,1], [170,1], [181,1], [177,1], [163,1]]
tall

[[177, 1], [183, 1], [170, 1], [181, 1], [177, 1], [163, 1]]

In [5]:
x = np.linalg.lstsq(tall, foot, rcond=None)
x

(array([   2.32089103, -139.04274533]),
 array([446.32751355]),
 2,
 array([4.29398406e+02, 9.49127132e-02]))

In [6]:
x[0] * 173 * x[1]

array([   179206.81137662, -10736138.28467727])

In [7]:
dict= {'name': 'alice', 'age': 25}

In [8]:
import pandas as pd

df = pd.DataFrame(
{"a" : [4, 5, 6, 7], 
"b" : [8, 9, 10, 11],
"C" : [12, 13, 14, 15]},
index=[1, 2, 3, 4]) 

df

a   b   C
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

In [9]:
df = pd.DataFrame(
{"a" : [4, 5, 6, 7], "b": [8, 9, 10, 11], "c" :[12 ,13, 14, 15]},

index=pd.MultiIndex.from_tuples(
[('d', 1), ('d', 2), ('e', 1), ('e', 2)],

names=['n', 'v']))

df

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [10]:
df.rename(columns={'c':'d'})
df.reset_index()

n  v  a   b   c
0  d  1  4   8  12
1  d  2  5   9  13
2  e  1  6  10  14
3  e  2  7  11  15

In [ ]:
# 인덱스를 오름차순으로 정렬
df.sort_index()

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [12]:
df.drop(columns=['a','b'])

c
n v    
d 1  12
  2  13
e 1  14
  2  15

In [13]:
df.head(2)

a  b   c
n v          
d 1  4  8  12
  2  5  9  13

In [14]:
df.tail(2)

a   b   c
n v           
e 1  6  10  14
  2  7  11  15

In [15]:
df[df["a"]>4]

a   b   c
n v           
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [16]:
df[df["a"] == 6]

a   b   c
n v           
e 1  6  10  14

In [17]:
df[df["a"] != 5]

a   b   c
n v           
d 1  4   8  12
e 1  6  10  14
  2  7  11  15

In [18]:
df[df['a'].isin([4])]

a  b   c
n v          
d 1  4  8  12

In [19]:
df.sample(frac=0.75)

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

In [20]:
df.sample(n=3)

a   b   c
n v           
e 2  7  11  15
d 1  4   8  12
e 1  6  10  14

In [21]:
df.nlargest(3, 'a')

a   b   c
n v           
e 2  7  11  15
  1  6  10  14
d 2  5   9  13

In [22]:
df.iloc[1:4]

a   b   c
n v           
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

In [23]:
df.iloc[2:]

a   b   c
n v           
e 1  6  10  14
  2  7  11  15

In [24]:
df.loc[df['a']>5, ['a', 'c']]

a   c
n v       
e 1  6  14
  2  7  15

In [25]:
df.loc[:,'a':'c']

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [26]:
df

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [ ]:
# 1번째 행, 1번째 열에 위치한 단일 셀 값을 가져옵니다
df.iat[1,1]

9

In [28]:
df = pd.DataFrame(
{"a" : [4, 5, 6, 7, 7], "b": [8, 9, 10, 11, 11], "c" :[12 ,13, 14, 15, 15]},

index=pd.MultiIndex.from_tuples(
[('d', 1), ('d', 2), ('e', 1), ('e', 2), ('e', 3)],

names=['n', 'v']))

df

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15
  3  7  11  15

In [29]:
df['a'].value_counts()

a
7    2
4    1
5    1
6    1
Name: count, dtype: int64

In [30]:
len(df)

5

In [ ]:
df.shape
# 결과는 (행의 수, 열의 수) 형태의 튜플(tuple)

(4, 6)

In [32]:
# df['a'] 열(column)에서 고유한(unique) 값의 개수
df['a'].nunique()

4

In [33]:
df.describe()

a         b         c
count  5.00000   5.00000   5.00000
mean   5.80000   9.80000  13.80000
std    1.30384   1.30384   1.30384
min    4.00000   8.00000  12.00000
25%    5.00000   9.00000  13.00000
50%    6.00000  10.00000  14.00000
75%    7.00000  11.00000  15.00000
max    7.00000  11.00000  15.00000

In [34]:
# 중복된 행(row)을 제거
df = df.drop_duplicates()
df

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [35]:
df.sum()

a    22
b    38
c    54
dtype: int64

In [36]:
df.count()

a    4
b    4
c    4
dtype: int64

In [37]:
df.median()

a     5.5
b     9.5
c    13.5
dtype: float64

In [38]:
df.mean()

a     5.5
b     9.5
c    13.5
dtype: float64

In [39]:
import numpy as np

# 제곱근
df.apply(np.sqrt)

a         b         c
n v                              
d 1  2.000000  2.828427  3.464102
  2  2.236068  3.000000  3.605551
e 1  2.449490  3.162278  3.741657
  2  2.645751  3.316625  3.872983

In [40]:
df = pd.DataFrame(
{"a" : [4, 5, 6, np.nan], "b": [7, 8, np.nan, 9], "c" :[10, np.nan, 11, 12]},

index=pd.MultiIndex.from_tuples(
[('d', 1), ('d', 2), ('e', 1), ('e', 2) ],

names=['n', 'v']))

df

a    b     c
n v                
d 1  4.0  7.0  10.0
  2  5.0  8.0   NaN
e 1  6.0  NaN  11.0
  2  NaN  9.0  12.0

In [ ]:
# null값이면 true를 반환
pd.isnull(df)

a      b      c
n v                     
d 1  False  False  False
  2  False  False   True
e 1  False   True  False
  2   True  False  False

In [ ]:
# null값이면 false를 반환
pd.notnull(df)

a      b      c
n v                     
d 1   True   True   True
  2   True   True  False
e 1   True  False   True
  2  False   True   True

In [43]:
df.notnull = df.dropna()
df

a    b     c
n v                
d 1  4.0  7.0  10.0
  2  5.0  8.0   NaN
e 1  6.0  NaN  11.0
  2  NaN  9.0  12.0

In [44]:
df_fillna = df.fillna(13)
df_fillna

a     b     c
n v                  
d 1   4.0   7.0  10.0
  2   5.0   8.0  13.0
e 1   6.0  13.0  11.0
  2  13.0   9.0  12.0

In [45]:
df = pd.DataFrame(
{"a" : [4, 5, 6, 7], "b": [8, 9, 10, 11], "c" :[12 ,13, 14, 15]},

index=pd.MultiIndex.from_tuples(
[('d', 1), ('d', 2), ('e', 1), ('e', 2)],

names=['n', 'v']))

df

a   b   c
n v           
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

In [46]:
df['sum'] = df['a'] + df['b'] + df['c']
df

a   b   c  sum
n v                
d 1  4   8  12   24
  2  5   9  13   27
e 1  6  10  14   30
  2  7  11  15   33

In [47]:
# 새로운 열 multiply를 추가
df = df.assign(multiply=lambda df: df['a']*df['b']*df['c']) 
df

a   b   c  sum  multiply
n v                          
d 1  4   8  12   24       384
  2  5   9  13   27       585
e 1  6  10  14   30       840
  2  7  11  15   33      1155

In [48]:
# a 열의 값을 5 이상 6 이하로 자른(clipping) 결과를 clip이라는 새로운 열로 추가
df['clip'] = df['a'].clip(lower=5, upper=6)
df

a   b   c  sum  multiply  clip
n v                                
d 1  4   8  12   24       384     5
  2  5   9  13   27       585     5
e 1  6  10  14   30       840     6
  2  7  11  15   33      1155     6

In [49]:
# 데이터프레임에서 각 열(column)마다의 최댓값을 반환
df.max(axis=0)

a              7
b             11
c             15
sum           33
multiply    1155
clip           6
dtype: int64

In [50]:
df1 = pd.DataFrame([
    {'letter': 'a', 'number': 1},
    {'letter': 'b', 'number': 2}
])

In [52]:
df2 = pd.DataFrame([
    {'letter': 'c', 'number': 3},
    {'letter': 'd', 'number': 4}
])

In [54]:
df3 = pd.DataFrame([
    {'letter': 'e', 'number': 5, 'animal': 'cat'},
    {'letter': 'f', 'number': 6, 'animal': 'dog'}
])